# Generated by Django 2.1.7 on 2019-09-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('edad', models.IntegerField()),
                ('foto', models.ImageField(upload_to='images/')),
                ('descripcion', models.TextField()),
                ('telefono', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('edad', models.IntegerField()),
                ('foto', models.ImageField(upload_to='images/')),
                ('descripcion', models.TextField()),
                ('telefono', models.TextField()),
                ('paginaWeb', models.TextField()),
                ('contactoRS', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
