# Generated by Django 2.1.7 on 2019-09-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nombreUsuario',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombreUsuario',
            field=models.TextField(default='', unique=True),
        ),
    ]
