# Generated by Django 2.1.7 on 2019-10-01 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='fechaPregunta',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 23, 27, 3, 469706)),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='fechaRespuesta',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 23, 27, 3, 469745)),
        ),
    ]
