# Generated by Django 2.1.7 on 2019-10-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritocompras',
            name='servicios',
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='lista_servicios',
            field=models.ManyToManyField(related_name='servicios', through='servicios.Carrito_servicio', to='servicios.Servicio'),
        ),
    ]
