# Generated by Django 2.1.7 on 2019-09-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20190915_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='foto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='foto',
            field=models.TextField(),
        ),
    ]
