# Generated by Django 2.1.7 on 2019-10-01 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20191001_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='fechaPregunta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='fechaRespuesta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
