# Generated by Django 2.1.7 on 2019-09-17 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('servicios', '0003_auto_20190915_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carr_Serv_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numServicios', models.IntegerField()),
                ('costoTotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroTarjeta', models.TextField()),
                ('cvv', models.TextField()),
                ('banco', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('pais', models.TextField()),
                ('ciudad', models.TextField()),
                ('idioma', models.TextField()),
                ('costo', models.FloatField()),
                ('descripcion', models.TextField()),
                ('foto', models.TextField()),
                ('numeroPersonas', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicios.Servicio')),
                ('tipoComida', models.TextField()),
                ('cantidadPlatos', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('servicios.servicio',),
        ),
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicios.Servicio')),
                ('tipoAlojamiento', models.TextField(choices=[('HOTEL', 'Hotel'), ('CASA', 'Casa'), ('CAMPING', 'Camping'), ('MOTEL', 'Motel')])),
                ('numeroHabitaciones', models.IntegerField()),
                ('numeroBanos', models.IntegerField()),
                ('servicioLimpieza', models.TextField(choices=[('Si', 'Si'), ('No', 'No')])),
                ('servicioWifi', models.TextField(choices=[('Si', 'Si'), ('No', 'No')])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('servicios.servicio',),
        ),
        migrations.CreateModel(
            name='PaseoEcologico',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicios.Servicio')),
                ('origen', models.TextField()),
                ('horaInicio', models.DateField()),
                ('horaFin', models.DateField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('servicios.servicio',),
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicios.Servicio')),
                ('empresa', models.TextField()),
                ('tipoTransporte', models.TextField(choices=[('TERRESTRE', 'Terrestre'), ('AEREO', 'Aereo'), ('MARITIMO', 'Maritimo')])),
                ('origen', models.TextField()),
                ('destino', models.TextField()),
                ('horaSalida', models.DateField()),
                ('horaLlegada', models.DateField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('servicios.servicio',),
        ),
        migrations.RenameModel(
            old_name='Client',
            new_name='Cliente',
        ),
        migrations.AddField(
            model_name='servicio',
            name='Proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Proveedor'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_servicios.servicio_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='resena',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Cliente'),
        ),
        migrations.AddField(
            model_name='resena',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Servicio'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Cliente'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Servicio'),
        ),
        migrations.AddField(
            model_name='metododepago',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Cliente'),
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicios.Cliente'),
        ),
        migrations.AddField(
            model_name='carr_serv_rel',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.CarritoCompras'),
        ),
        migrations.AddField(
            model_name='carr_serv_rel',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Servicio'),
        ),
    ]
