# Generated by Django 2.1.7 on 2019-10-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20191002_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='paseoecologico',
            name='destino',
            field=models.TextField(default=''),
        ),
    ]
