# Generated by Django 2.1.7 on 2019-09-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20190917_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentacion',
            name='cantidadPlatos',
            field=models.IntegerField(),
        ),
    ]
