# Generated by Django 2.1.7 on 2019-10-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_paseoecologico_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carr_serv_rel',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carr_serv_rel',
            name='servicio',
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='servicios',
            field=models.ManyToManyField(to='servicios.Servicio'),
        ),
        migrations.DeleteModel(
            name='Carr_Serv_rel',
        ),
    ]
