# Generated by Django 2.1.7 on 2019-10-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20191002_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='horaLlegada',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='horaSalida',
            field=models.TextField(),
        ),
    ]
