# Generated by Django 2.1.7 on 2019-10-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_auto_20191002_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paseoecologico',
            name='horaFin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paseoecologico',
            name='horaInicio',
            field=models.TextField(),
        ),
    ]
