# Generated by Django 2.1.7 on 2019-09-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_auto_20190917_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.TextField(default='1234'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contrasena',
            field=models.TextField(default='1234'),
        ),
    ]
