# Generated by Django 2.1.7 on 2019-10-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_auto_20191002_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='fechaPregunta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='fechaRespuesta',
            field=models.TextField(),
        ),
    ]
