# Generated by Django 2.1.7 on 2019-10-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_auto_20191002_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metododepago',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='MetodoDePago',
        ),
    ]
